### PR TITLE
Add filereceiver component with updated functionality

### PR DESCRIPTION
**Pull request by moh-osman3**
What does this PR do?
This PR is part 2 of https://github.com/f5/otel-arrow-adapter/pull/185
Adds the filereceivercomponent directly rather than using the component currently in opentelemetry-collector-contrib package.

Adding the component directly allows us to use the functionality from this https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22080 open in the contrib repository. This contrib PR is taking a while to get approved so in the meantime it might be better to add these changes to start using these components to replay data in production.

Example config:
```
receivers:
  file:
    path: ../../gen/receiver/filereceiver/testdata/metrics.json
    compression: zstd
    format: json
```
Testing
Ran the cmd/otelarrowcol with the filereceiver component and successfully read from file in the desired format/compression

(cc: @jmacd)

### CODE REVIEW

**Review by jmacd — APPROVED** [review]
I expect this to be short-lived, as we wait for the contrib repo to accept & review this functionality. Until then, it will be nice to be able to run telemetry-generator from in-repo components. Thanks @moh-osman3

**Comment by lquerel** [comment]
@moh-osman3 there are some conflicts to resolve that prevent to merge this PR.

**Comment by moh-osman3** [comment]
@lquerel rebased and fixed the conflict. Thank you!

**Comment by lquerel** [comment]
LGTM

**Pull request merged**
